name: Validate & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install Poetry
      #uses: abatilo/actions-poetry@v2.1.0  # Pinned to SHA hash
      uses: abatilo/actions-poetry@8284d202bc272a8d0597e26e1c0b4a0d0c73db93
      with:
        poetry-version: 1.1.4
    - name: Install Dependencies
      run: |
        poetry install
    - name: Check Formatting
      run: |
        poetry run black --check src tests
    - name: Test
      run: |
        poetry run pytest tests
